version: '3.9'

services:
  app:
    container_name: react-bootstrap-dockerised
    image: node:18.15.0-alpine
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - '8080:8080'
